# Generated by Django 2.0.8 on 2018-08-09 17:34
from django.db import migrations

import settings
from db.core.models import BaseUser


def create_superuser(apps, schema_editor):
    superuser = BaseUser(
        is_active=True, is_superuser=True, is_staff=True, email=settings.SUPERUSER_EMAIL
    )
    superuser.set_password(settings.SUPERUSER_PASS)
    superuser.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]
    operations = [migrations.RunPython(create_superuser)]
